# User properties
code.page=65001
toolbar.usestockicons=1
title.full.path=1
title.show.buffers=1

save.recent=1
save.session=1
session.bookmarks=1
session.folds=1

# Ask for reload if file is changed in outer application/editor
load.on.activate=1
are.you.sure.on.reload=1

autocompleteword.automatic=1

filter.match.indicator=style:roundbox,colour:#FFFFAA,under,outlinealpha:140,fillalpha:90
find.replace.advanced=1
find.replace.regexp=1
find.replace.regexp.posix=1
open.dialog.in.file.directory=1

# Column guide, indicates long lines
edge.mode=1
edge.column=80

use.tabs=0
tabsize=4
indent.size=4
#  strip.trailing.spaces=1


imports.exclude=abaqus ada asciidoc asl asn1 au3 ave avs baan blitzbasic bullant \
caml cil cmake cobol coffeescript csound d dataflex ecl eiffel Embedded erlang escript \
flagship forth fortran freebasic fsharp \
gap haskell hex hollywood inno kix latex lisp lot lout \
matlab maxima metapost mmixal modula3 nim nimrod nncrontab nsis \
opal oscript pascal perl pov powerpro ps purebasic r raku rebol \
sas scriptol smalltalk sorcins spice specman \
tacl tal tcl tex troff txt2tags vb verilog vhdl visualprolog


[OUTPUT]
split.vertical=1
output.initial.hide=1
output.magnification=1
output.horizontal.size=740
output.vertical.size=80
clear.before.execute=1

# Cursor stays at the bottom after execution
output.scroll=2
# Shows time of execution - different than Python time measurements (a little bit bigger))
time.commands=1
# To see error messages interspersed with the source code, set error.inline=1 and press F4
#  error.inline=1
error.select.line=1
error.jump.to.first=1


[MULTIPLE SELECTIONS]
# -- Set to 1 to allow movin to virtual space when making a rectangular selection.
# -- 2 allows arowKeys/Mouse to operate in Multiple Selections
# -- 3 allow 1 and 2
# virtual.space=3

# -- Allow multiple Selections with Alt and Mouse.
selection.multiple=1
# -- Allow typing backspace and delete in Multiple Selections
selection.additional.typing=1
# -- Allow to paste at all selections
selection.multipaste=1

selection.rectangular.switch.mouse=1



# --- Set  view.indentation.examine to 1 to display guides within real indentation whitespace only,
# --- Set to 2  to display whitespace according to the next non-empty line (good for Python)
# --- or  3 according to both the next and previous non-empty lines (good for most languages).
view.indentation.examine=3
# --- Set view.indentation.guides  to 1  display dotted vertical lines within indentation white space every  -> indent.size columns.
view.indentation.guides=1
# ---- Setting highlight.indentation.guides to 1 highlights the indentation guide associated with a selected brace
highlight.indentation.guides=1


[🎨 STYLES]

if PLAT_WIN
    font.base=font:Consolas,size:12
    font.small=font:Consolas,size:10
    font.comment=font:Courier New,size:12
    font.code.comment.box=$(font.comment)
    font.code.comment.line=$(font.comment)
    font.code.comment.doc=$(font.comment)
    font.code.comment.nested=$(font.comment)
    font.text=font:Cambria,size:10
    font.text.comment=font:Serif,size:9
    font.embedded.base=font:Serif,size:9
    font.embedded.comment=font:Serif,size:9
    font.monospace=font:Consolas,size:9
    font.monospace.small=font:Consolas,size:8
    font.vbs=font:Courier New,size:10

if PLAT_GTK
    font.base=font:Fira Code,size:14
    font.small=font:Fira Code,size:12
    font.comment=font:Monospace,size:12
    font.code.comment.box=$(font.comment)
    font.code.comment.line=$(font.comment)
    font.code.comment.doc=$(font.comment)
    font.code.comment.nested=$(font.comment)
    font.text=font:Serif,size:10
    font.text.comment=font:Serif,size:10
    font.embedded.base=font:Serif,size:10
    font.embedded.comment=font:Serif,size:10
    font.monospace=font:Monospace,size:12
    font.monospace.small=font:Monospace,size:10
    font.vbs=font:DejaVu Sans Mono,size:9


[🎨 COLORS]
#  Give symbolic names to the set of colours used in the standard styles.
colour.code.comment.box=fore:#808080
colour.code.comment.line=fore:#808080
colour.code.comment.doc=fore:#808080
colour.code.comment.nested=fore:#808080

colour.number=fore:#ff2200
colour.keyword=fore:#00557f
colour.string=fore:#007400
colour.operator=fore:#00aa7f

[Global default styles for all languages]
# Default
style.*.32=$(font.base),back:#f8f8f8


[OUTPUT PANE]
#  style.errorlist.32=$(font.small),back:#efffef
style.errorlist.32=font:Fira Code,size:8,back:#efffef
style.errorlist.0=fore:#383838

# Error  0 default / 1 warning / 2 error / 3 fatal
# error.marker.fore=#550403
# error.marker.back=#550403
style.error.0=$(colour.default),$(font.monospace)
style.error.1=fore:#A48850,$(font.monospace),size:7,bold,
style.error.2=fore:#A45540,$(font.monospace),size:7,bold
style.error.3=fore:#A43335,$(font.monospace),size:7,bold

# Calltip Python style
style.python.38=fore:#383838,back:#D1EEFF3F,$(font.small)

# Caret
caret.fore=#FF0000
caret.style=1
caret.width=3

#🎨 Line highlighting colors
#--------------------------------
caret.line.back=#FFFED83F
# caret.line.back=#D7FFE9
# caret.line.back=#EFEFEF
caret.line.frame=1

line.margin.visible=1
line.margin.width=3+

selection.layer=2
# selection.fore=#cc2200
# selection.back=#ffa00050
selection.additional.back=#00000010
selection.inactive.back=#00000010
selection.additional.fore=#00A000
selection.inactive.fore=#00A000
selection.secondary.fore=#A00000
selection.always.visible=1

whitespace.fore=#FF0000
whitespace.back=#FFF0F0
whitespace.size=2

#fold.compact=1
fold.flags=16
fold.line.colour=#80800080
fold.symbols=2
#fold.fore=#000000
#fold.back=#808080
fold.highlight=1
fold.highlight.colour=#00C0C0
#fold.stroke.width=200

# --- If set, then the Mark All command in the Find dialog will draw indicators over each string found.
# --- See SciTEDoc.html#IndicatorProperty
wrap.visual.flags.location=2
find.mark.indicator=style:roundbox,colour:#FF8100,under,outlinealpha:140,fillalpha:80

highlight.current.word=1
highlight.current.word.indicator=style:compositionthick,colour:#FF3500,under,outlinealpha:140,fillalpha:80
#  highlight.current.word.indicator=style:roundbox,colour:#FF8100,under,outlinealpha:140,fillalpha:80


[SHORTCUTS]
user.shortcuts=\
Ctrl+Shift+J|IDM_JOIN|\
Ctrl+Shift+Up|2620|\
Ctrl+Shift+Down|2621|\
Ctrl+K|2338|\
Ctrl+9|IDM_BOOKMARK_TOGGLE|\
Shift+F8|IDM_CLEAROUTPUT|\
Shift+F5|IDM_STOPEXECUTE|\
Ctrl+Shift+KeypadMinus|IDM_TOGGLE_FOLDALL|\


[CONTEXT MENU]
user.context.menu=\
||\
⚙️ User Properties|IDM_OPENUSERPROPERTIES|\
⚙️ Lua Startup Script|IDM_OPENLUAEXTERNALFILE|\
📌 Abbreviations|IDM_OPENABBREVPROPERTIES|\
|---|\
📑 Copy as RTF|IDM_COPYASRTF|\
|----|\
➡️ Extract SELECTED Patterns|1116|\
➡️ Extract CONTAINED Patterns|1117|\
➡️ Extract CONTAINED Lines|1118|\
➡️ Extract REGEX Patterns|1119|\
➡️ Extract Find Results|1120|\
|----|\
🔒 BASE64 Encode|1137|\
🔐 BASE64 Decode|1138|\
|----|\
📃 JSON Prettify|1141|\
📃 SQL Format|1143|


[MENU SHORTCUTS]
*language.sql=SQL|sql|Ctrl+Shift+F8|
*language.python=Python|py|Ctrl+Shift+F9|
*language.rust=Rust|rs|Ctrl+Shift+F10|
*language.json=JSON|json|Ctrl+Shift+F7|


[STATUS BAR]
statusbar.visible=1
statusbar.number=1
statusbar.text.1=\
📌 Line: $(LineNumber) / $(NbOfLines) | Column: $(ColumnNumber)  🔤 SELECTED Chars: $(SelLength) | Lines: $(SelHeight)    ⌨️ $(OverType) ($(EOLMode)) $(FileAttr) | 💾️ $(Language)    🔍 = $(ZoomFactor)


[SCRIPTING]
ext.lua.startup.script=$(SciteUserHome)/.config/Scite_scripts/SciTEStartup.lua


[LUA COMMAND SHORTCUTS]
command.name.12.*=📆 Insert Date
command.mode.12.*=subsystem:lua,savebefore:no
command.12.*=insert_timestamp
command.shortcut.12.*=Ctrl+F5

command.name.16.*=
#  command.name.16.*=➡️ Extract SELECTED Patterns
command.mode.16.*=subsystem:lua,savebefore:no
command.16.*=print_selected_patterns
#  command.shortcut.16.*=Ctrl+Alt+1

command.name.17.*=
# command.name.17.*=➡️️ Extract CONTAINED Patterns
command.mode.17.*=subsystem:lua,savebefore:no
command.17.*=print_contained_patterns
command.shortcut.17.*=Ctrl+Alt+2

command.name.18.*=
# command.name.18.*=➡️️ Extract CONTAINED Lines
command.mode.18.*=subsystem:lua,savebefore:no
command.18.*=print_contained_lines
# command.shortcut.18.*=Ctrl+Alt+3

command.name.19.*=
#  command.name.19.*=➡️️ Extract REGEX Patterns
command.mode.19.*=subsystem:lua,savebefore:no
command.19.*=print_matched_patterns
#  command.shortcut.19.*=Ctrl+Alt+4

command.name.20.*=
#  command.name.20.*=➡️️ Extract Find Results
command.mode.20.*=subsystem:lua,savebefore:no
command.20.*=print_marked_lines
#  command.shortcut.20.*=Ctrl+Alt+5

command.name.26.*=🗑️ Remove Duplicates
command.mode.26.*=subsystem:lua,savebefore:no
command.26.*=remove_duplicates
command.shortcut.26.*=Ctrl+0

command.name.27.*=🗑️ Delete Empty Lines
command.mode.27.*=subsystem:lua,savebefore:no
command.27.*=del_empty_lines
command.shortcut.27.*=Ctrl+Alt+0

command.name.28.*=🗑️ Strip Trailing Spaces
command.mode.28.*=subsystem:lua,savebefore:no
command.28.*=stripTrailingSpaces
command.shortcut.28.*=Ctrl+.

command.name.29.*=↩️ Transpose to Line
command.mode.29.*=subsystem:lua,savebefore:no
command.29.*=tran_2_line
command.shortcut.29.*=Ctrl+Alt+;

command.name.30.*=↔️ Split String
command.mode.30.*=subsystem:lua,savebefore:no
command.30.*=split_words
command.shortcut.30.*=Ctrl+Alt+'

command.name.31.*=↔️ Split String (SQL)
command.mode.31.*=subsystem:lua,savebefore:no
command.31.*=split
command.shortcut.31.*=Ctrl+Alt+7

command.name.32.*=↩️ Transpose to Line (SQL)
command.mode.32.*=subsystem:lua,savebefore:no
command.32.*=transpose_2_line
command.shortcut.32.*=Ctrl+Alt+8

command.name.33.*=ℹ️ Show duplicate lines
command.mode.33.*=subsystem:lua,savebefore:no
command.33.*=duplicate_lines
command.shortcut.33.*=Ctrl+Alt+D

command.name.34.*=ℹ️ Show duplicate lines with freq
command.mode.34.*=subsystem:lua,savebefore:no
command.34.*=duplicate_lines_freq
command.shortcut.34.*=Ctrl+Alt+#

command.name.35.*=ℹ️ Show unique lines
command.mode.35.*=subsystem:lua,savebefore:no
command.35.*=unique_lines
command.shortcut.35.*=Ctrl+Alt+-

command.name.36.*=🔒 BASE64 Encode
command.mode.36.*=subsystem:lua,savebefore:no
command.36.*=b64enc
command.shortcut.36.*=Ctrl+Alt+B

command.name.37.*=🔐 BASE64 Decode
command.mode.37.*=subsystem:lua,savebefore:no
command.37.*=b64dec
command.shortcut.37.*=Ctrl+Shift+B

command.name.38.*=🔁 Tabs_2_Spaces
command.mode.38.*=subsystem:lua,savebefore:no
command.38.*=tabs_to_spaces_obey_tabstop
command.shortcut.38.*=Ctrl+Alt++

command.name.39.*=📃 Make API description
command.mode.39.*=subsystem:lua,savebefore:no
command.39.*=trans_2_line
command.shortcut.39.*=Ctrl+Shift+F2

[Pretty Print JSON]

### No Lua Example - no cleansing and fixing. Works on correct json files
command.name.41.*=📃 JSON Pretty Print
command.mode.41.*=subsystem:0,savebefore:no
command.replace.selection.41.*=1
command.quiet.41.*=1
command.41.*=jq "." <<< '$(CurrentSelection)'
command.shortcut.41.*=Ctrl+Shift+F7

#  For Large JSON files
command.name.42.*=📃 Pretty Print JSON file
command.mode.42.*=subsystem:0,savebefore:no
command.replace.selection.42.*=1
command.quiet.42.*=1
command.42.*=jq "." "$(FileNameExt)"
command.shortcut.42.*=Ctrl+Alt+J

# Format SQL
command.name.43.*=📃 Sleek SQL Format
command.mode.43.*=subsystem:console,savebefore:no
command.replace.selection.43.*=1
command.43.*=sleek -U true <<< """$(CurrentSelection)"""
command.quiet.43.*=1
command.shortcut.43.*=Ctrl+Alt+Q

command.name.44.*=📃 Format SQL file
command.mode.44.*=subsystem:0,savebefore:no
command.replace.selection.44.*=1
command.quiet.44.*=1
command.44.*=sleek "$(FilePath)"
command.shortcut.44.*=Ctrl+Alt+L

# Transpose text
command.name.45.*=🔁 TransposeText
command.mode.45.*=subsystem:lua,savebefore:no
command.45.*=transposeText
command.shortcut.45.*=Ctrl+Alt+Y

command.name.46.*=🔡 AlignColumns
command.mode.46.*=subsystem:lua,savebefore:no
command.46.*=align_columns
command.shortcut.46.*=Ctrl+Shift+|

command.name.47.*=📊 Align CSV
command.mode.47.*=subsystem:lua,savebefore:no
command.47.*=StripDlg func=AlignCSV dlg='AlignCSV:'[]((OK))
command.shortcut.47.*=Ctrl+Alt+C

command.name.48.*=🟰 Align On
command.mode.48.*=subsystem:lua,savebefore:no
command.48.*=StripDlg func=AlignOnMulti dlg='AlignOnMulti:'[]((OK))
command.shortcut.48.*=Ctrl+Alt+=
